# Form implementation generated from reading ui file 'tablewidgetexample.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import pymysql as mdb

class Ui_tableWidgetExample(object):
    def setupUi(self, tableWidgetExample):
        tableWidgetExample.setObjectName("tableWidgetExample")
        tableWidgetExample.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        tableWidgetExample.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=tableWidgetExample)
        self.centralwidget.setObjectName("centralwidget")
        self.btnDisplay = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDisplay.setGeometry(QtCore.QRect(330, 110, 93, 28))
        self.btnDisplay.setObjectName("btnDisplay")
        self.tblStudentData = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tblStudentData.setGeometry(QtCore.QRect(120, 170, 521, 241))
        self.tblStudentData.setObjectName("tblStudentData")
        self.tblStudentData.setColumnCount(0)
        self.tblStudentData.setRowCount(0)
        tableWidgetExample.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=tableWidgetExample)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        tableWidgetExample.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=tableWidgetExample)
        self.statusbar.setObjectName("statusbar")
        tableWidgetExample.setStatusBar(self.statusbar)

        self.retranslateUi(tableWidgetExample)
        QtCore.QMetaObject.connectSlotsByName(tableWidgetExample)
        
        self.load_data("student_data.txt")

    def load_data(self, filename):
        try:
            connection = mdb.connect(host="localhost", port=3306, user="root", password="A1tamahaw03!", database= "student_scores")
            cursor = connection.cursor ()
            with open (filename, "r") as fname:
                for line in fname:
                    data = line.split (",")
                    #print(data)
                    cursor.execute ("insert into student_data (studentid, studentname, studentage, studentscore) values (%s, %s, %s, %s) ", [data[0] . strip() , data[1] . strip() , data [2] . strip() , data[3].strip() ])
                    connection.commit ()

        except Exception as e:
            print(e)
        finally:
            if(connection):
                connection.close ()

    def retranslateUi(self, tableWidgetExample):
        _translate = QtCore.QCoreApplication.translate
        tableWidgetExample.setWindowTitle(_translate("tableWidgetExample", "Table Widget Example"))
        self.btnDisplay.setText(_translate("tableWidgetExample", "Display"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tableWidgetExample = QtWidgets.QMainWindow()
    ui = Ui_tableWidgetExample()
    ui.setupUi(tableWidgetExample)
    tableWidgetExample.show()
    sys.exit(app.exec())
