# Form implementation generated from reading ui file 'mortalcombat.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class player:
    def _init_(self, name, speed, power, agility):
        self.player_name = name
        self.player_speed = speed
        self.player_power = power
        self.player_agility = agility
        
    def modify_stats(self, speed, power, agility):
        self.player_speed = speed
        self.player_power = power
        self.player_agility = agility
        

class Ui_mortalCombat(object):
    def setupUi(self, mortalCombat):
        mortalCombat.setObjectName("mortalCombat")
        mortalCombat.resize(970, 701)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        mortalCombat.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=mortalCombat)
        self.centralwidget.setObjectName("centralwidget")
        self.tbMortalCombat = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tbMortalCombat.setGeometry(QtCore.QRect(10, 0, 951, 671))
        self.tbMortalCombat.setObjectName("tbMortalCombat")
        self.tbCreatePlayer = QtWidgets.QWidget()
        self.tbCreatePlayer.setObjectName("tbCreatePlayer")
        self.lblName = QtWidgets.QLabel(parent=self.tbCreatePlayer)
        self.lblName.setGeometry(QtCore.QRect(30, 30, 141, 16))
        self.lblName.setObjectName("lblName")
        self.lblSpeed = QtWidgets.QLabel(parent=self.tbCreatePlayer)
        self.lblSpeed.setGeometry(QtCore.QRect(30, 90, 101, 31))
        self.lblSpeed.setObjectName("lblSpeed")
        self.lblPower = QtWidgets.QLabel(parent=self.tbCreatePlayer)
        self.lblPower.setGeometry(QtCore.QRect(30, 170, 101, 21))
        self.lblPower.setObjectName("lblPower")
        self.lblAgility = QtWidgets.QLabel(parent=self.tbCreatePlayer)
        self.lblAgility.setGeometry(QtCore.QRect(30, 230, 121, 31))
        self.lblAgility.setObjectName("lblAgility")
        self.btnCreate = QtWidgets.QPushButton(parent=self.tbCreatePlayer)
        self.btnCreate.setGeometry(QtCore.QRect(30, 310, 151, 28))
        self.btnCreate.setObjectName("btnCreate")
        self.txtName = QtWidgets.QLineEdit(parent=self.tbCreatePlayer)
        self.txtName.setGeometry(QtCore.QRect(200, 30, 113, 22))
        self.txtName.setObjectName("txtName")
        self.txtSpeed = QtWidgets.QLineEdit(parent=self.tbCreatePlayer)
        self.txtSpeed.setGeometry(QtCore.QRect(200, 90, 113, 22))
        self.txtSpeed.setObjectName("txtSpeed")
        self.txtPower = QtWidgets.QLineEdit(parent=self.tbCreatePlayer)
        self.txtPower.setGeometry(QtCore.QRect(200, 170, 113, 22))
        self.txtPower.setObjectName("txtPower")
        self.txtAgility = QtWidgets.QLineEdit(parent=self.tbCreatePlayer)
        self.txtAgility.setGeometry(QtCore.QRect(200, 230, 113, 22))
        self.txtAgility.setObjectName("txtAgility")
        self.tbMortalCombat.addTab(self.tbCreatePlayer, "")
        self.tbModifyPlayer = QtWidgets.QWidget()
        self.tbModifyPlayer.setObjectName("tbModifyPlayer")
        self.lblExistingPlayers = QtWidgets.QLabel(parent=self.tbModifyPlayer)
        self.lblExistingPlayers.setGeometry(QtCore.QRect(320, 20, 121, 31))
        self.lblExistingPlayers.setObjectName("lblExistingPlayers")
        self.lstExistingPlayers = QtWidgets.QListWidget(parent=self.tbModifyPlayer)
        self.lstExistingPlayers.setGeometry(QtCore.QRect(210, 60, 361, 321))
        self.lstExistingPlayers.setObjectName("lstExistingPlayers")
        self.txtCurrentSpeed = QtWidgets.QLineEdit(parent=self.tbModifyPlayer)
        self.txtCurrentSpeed.setGeometry(QtCore.QRect(120, 500, 113, 22))
        self.txtCurrentSpeed.setObjectName("txtCurrentSpeed")
        self.txtCurrentPower = QtWidgets.QLineEdit(parent=self.tbModifyPlayer)
        self.txtCurrentPower.setGeometry(QtCore.QRect(360, 500, 113, 22))
        self.txtCurrentPower.setObjectName("txtCurrentPower")
        self.txtCurrentAgility = QtWidgets.QLineEdit(parent=self.tbModifyPlayer)
        self.txtCurrentAgility.setGeometry(QtCore.QRect(600, 500, 113, 22))
        self.txtCurrentAgility.setObjectName("txtCurrentAgility")
        self.btnModify = QtWidgets.QPushButton(parent=self.tbModifyPlayer)
        self.btnModify.setGeometry(QtCore.QRect(350, 570, 131, 28))
        self.btnModify.setObjectName("btnModify")
        self.lblCurrentSpeed = QtWidgets.QLabel(parent=self.tbModifyPlayer)
        self.lblCurrentSpeed.setGeometry(QtCore.QRect(150, 460, 55, 16))
        self.lblCurrentSpeed.setObjectName("lblCurrentSpeed")
        self.lblCurrentPower = QtWidgets.QLabel(parent=self.tbModifyPlayer)
        self.lblCurrentPower.setGeometry(QtCore.QRect(390, 460, 55, 16))
        self.lblCurrentPower.setObjectName("lblCurrentPower")
        self.lblCurrentAgility = QtWidgets.QLabel(parent=self.tbModifyPlayer)
        self.lblCurrentAgility.setGeometry(QtCore.QRect(640, 460, 55, 16))
        self.lblCurrentAgility.setObjectName("lblCurrentAgility")
        self.tbMortalCombat.addTab(self.tbModifyPlayer, "")
        mortalCombat.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=mortalCombat)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 970, 25))
        self.menubar.setObjectName("menubar")
        mortalCombat.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=mortalCombat)
        self.statusbar.setObjectName("statusbar")
        mortalCombat.setStatusBar(self.statusbar)

        self.retranslateUi(mortalCombat)
        self.tbMortalCombat.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(mortalCombat)
        
        self.created_players = {}
        
        self.btnCreate.clicked.connect()
        
        self.btnCreate.clicked.connect(self.create_player)
        self.lstExistingPlayers.itemClciked.connect(self.display_stats)
        
    def display_stats(self):
        try:
            name = self.lstExistingPlayers.currentItem().text()
            player_object = self.created_players.get(name)
            self.txtCurrentSpeed.setText(f"{player_object.player_speed}")
            self.txtCurrentPower.setText(f"{player_object.player_power}")   
            self.txtCurrentAgility.setText(f"{player_object.player_agility}")
        except Exception as e:
            print(e)
            print(type(e))
            
            
    def create_player(self)
        try:
            name = self.txtName.text()
            speed = self.txtPower.text()
            power = self.txtPower.text()
            agility = self.txtAgility.text()
            
            player_object = player(name, speed, power, agility)
            self.created_players[name] = player_object
            self.lstExistingPlayers.addItem(name)
        except Exception as e:
            print(e)
            print(type(e))
            

    def retranslateUi(self, mortalCombat):
        _translate = QtCore.QCoreApplication.translate
        mortalCombat.setWindowTitle(_translate("mortalCombat", "Mortal Combat"))
        self.lblName.setText(_translate("mortalCombat", "Enter Name"))
        self.lblSpeed.setText(_translate("mortalCombat", "Enter Speed"))
        self.lblPower.setText(_translate("mortalCombat", "Enter Power"))
        self.lblAgility.setText(_translate("mortalCombat", "Enter Agility"))
        self.btnCreate.setText(_translate("mortalCombat", "Create Player"))
        self.tbMortalCombat.setTabText(self.tbMortalCombat.indexOf(self.tbCreatePlayer), _translate("mortalCombat", "Create Player"))
        self.lblExistingPlayers.setText(_translate("mortalCombat", "Existing Players"))
        self.btnModify.setText(_translate("mortalCombat", "Modify Player"))
        self.lblCurrentSpeed.setText(_translate("mortalCombat", "Speed"))
        self.lblCurrentPower.setText(_translate("mortalCombat", "Power"))
        self.lblCurrentAgility.setText(_translate("mortalCombat", "Agility"))
        self.tbMortalCombat.setTabText(self.tbMortalCombat.indexOf(self.tbModifyPlayer), _translate("mortalCombat", "Modify Player"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mortalCombat = QtWidgets.QMainWindow()
    ui = Ui_mortalCombat()
    ui.setupUi(mortalCombat)
    mortalCombat.show()
    sys.exit(app.exec())
