# Form implementation generated from reading ui file 'ticketpurchase.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_tbMainTab(object):
    def setupUi(self, tbMainTab):
        tbMainTab.setObjectName("tbMainTab")
        tbMainTab.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        tbMainTab.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=tbMainTab)
        self.centralwidget.setObjectName("centralwidget")
        self.tbPurchasesMade = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tbPurchasesMade.setGeometry(QtCore.QRect(0, 10, 771, 571))
        self.tbPurchasesMade.setObjectName("tbPurchasesMade")
        self.tbTicketPurchase = QtWidgets.QWidget()
        self.tbTicketPurchase.setObjectName("tbTicketPurchase")
        self.lblName = QtWidgets.QLabel(parent=self.tbTicketPurchase)
        self.lblName.setGeometry(QtCore.QRect(10, 20, 141, 16))
        self.lblName.setObjectName("lblName")
        self.txtName = QtWidgets.QLineEdit(parent=self.tbTicketPurchase)
        self.txtName.setGeometry(QtCore.QRect(200, 20, 113, 22))
        self.txtName.setObjectName("txtName")
        self.lblAge = QtWidgets.QLabel(parent=self.tbTicketPurchase)
        self.lblAge.setGeometry(QtCore.QRect(20, 80, 101, 21))
        self.lblAge.setObjectName("lblAge")
        self.txtAge = QtWidgets.QLineEdit(parent=self.tbTicketPurchase)
        self.txtAge.setGeometry(QtCore.QRect(200, 90, 113, 22))
        self.txtAge.setObjectName("txtAge")
        self.lblTicketType = QtWidgets.QLabel(parent=self.tbTicketPurchase)
        self.lblTicketType.setGeometry(QtCore.QRect(10, 160, 131, 31))
        self.lblTicketType.setObjectName("lblTicketType")
        self.cmbTicketType = QtWidgets.QComboBox(parent=self.tbTicketPurchase)
        self.cmbTicketType.setGeometry(QtCore.QRect(220, 170, 121, 22))
        self.cmbTicketType.setObjectName("cmbTicketType")
        self.cmbTicketType.addItem("")
        self.cmbTicketType.addItem("")
        self.cmbTicketType.addItem("")
        self.btnCalculate = QtWidgets.QPushButton(parent=self.tbTicketPurchase)
        self.btnCalculate.setGeometry(QtCore.QRect(10, 250, 93, 28))
        self.btnCalculate.setObjectName("btnCalculate")
        self.btnPurchase = QtWidgets.QPushButton(parent=self.tbTicketPurchase)
        self.btnPurchase.setGeometry(QtCore.QRect(210, 250, 93, 28))
        self.btnPurchase.setObjectName("btnPurchase")
        self.btnClear = QtWidgets.QPushButton(parent=self.tbTicketPurchase)
        self.btnClear.setGeometry(QtCore.QRect(400, 250, 93, 28))
        self.btnClear.setObjectName("btnClear")
        self.btnExit = QtWidgets.QPushButton(parent=self.tbTicketPurchase)
        self.btnExit.setGeometry(QtCore.QRect(600, 250, 93, 28))
        self.btnExit.setObjectName("btnExit")
        self.lblCost = QtWidgets.QLabel(parent=self.tbTicketPurchase)
        self.lblCost.setGeometry(QtCore.QRect(150, 360, 131, 20))
        self.lblCost.setObjectName("lblCost")
        self.txtCost = QtWidgets.QLineEdit(parent=self.tbTicketPurchase)
        self.txtCost.setGeometry(QtCore.QRect(330, 360, 113, 22))
        self.txtCost.setReadOnly(True)
        self.txtCost.setObjectName("txtCost")
        self.grpNumberofTickets = QtWidgets.QGroupBox(parent=self.tbTicketPurchase)
        self.grpNumberofTickets.setGeometry(QtCore.QRect(450, 50, 241, 80))
        self.grpNumberofTickets.setObjectName("grpNumberofTickets")
        self.rd1 = QtWidgets.QRadioButton(parent=self.grpNumberofTickets)
        self.rd1.setGeometry(QtCore.QRect(10, 30, 95, 20))
        self.rd1.setObjectName("rd1")
        self.radioButton = QtWidgets.QRadioButton(parent=self.grpNumberofTickets)
        self.radioButton.setGeometry(QtCore.QRect(70, 30, 95, 20))
        self.radioButton.setObjectName("radioButton")
        self.rd3 = QtWidgets.QRadioButton(parent=self.grpNumberofTickets)
        self.rd3.setGeometry(QtCore.QRect(130, 30, 95, 20))
        self.rd3.setObjectName("rd3")
        self.tbPurchasesMade.addTab(self.tbTicketPurchase, "")
        self.tbPurchasesMade1 = QtWidgets.QWidget()
        self.tbPurchasesMade1.setObjectName("tbPurchasesMade1")
        self.lstPurchaseMade = QtWidgets.QListWidget(parent=self.tbPurchasesMade1)
        self.lstPurchaseMade.setGeometry(QtCore.QRect(65, 80, 661, 381))
        self.lstPurchaseMade.setObjectName("lstPurchaseMade")
        self.lblPurchasesMade = QtWidgets.QLabel(parent=self.tbPurchasesMade1)
        self.lblPurchasesMade.setGeometry(QtCore.QRect(310, 40, 161, 20))
        self.lblPurchasesMade.setObjectName("lblPurchasesMade")
        self.tbPurchasesMade.addTab(self.tbPurchasesMade1, "")
        tbMainTab.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=tbMainTab)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        tbMainTab.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=tbMainTab)
        self.statusbar.setObjectName("statusbar")
        tbMainTab.setStatusBar(self.statusbar)

        self.retranslateUi(tbMainTab)
        self.tbPurchasesMade.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(tbMainTab)
        
        self.price_data = {}
        
        self.load_data("price.txt")
        
        self.btnCalculate.clicked.connect()
        
    def calculate_cost(self):
        try:
            current_selection = self.cmbTicketType.currentText()
            if(self.rd2.isChecked()):
                number_of_tickets = 2
            elif(self.rd3.isChecked()):
                number_of_tickets = 3
            else:
                number_of_tickets = 1
                
            price = self.price_data.get(current_selection)
            
            cost = price*number_of_tickets
            
            self.txtCost.setText(f"${cost.2f}")
        except:
            print("there was an unexpected error")
        finally: 
            print("closing any open DB connections")
            
        
        
    def load_data(self, filename):
        try:
            with open(filename, "r") as f:
                for line in f:
                    data = lin.split(",")
                    self.price_data[data[0]] = int(data[1])
        except FileNotFoundError:
            print("The file could not be opened")
        except:
            print("There was an unexpected error")
        finally:
            print("Closing any open DB connections")
                
                     

    def retranslateUi(self, tbMainTab):
        _translate = QtCore.QCoreApplication.translate
        tbMainTab.setWindowTitle(_translate("tbMainTab", "Ticket Purchase"))
        self.lblName.setText(_translate("tbMainTab", "Enter Name"))
        self.lblAge.setText(_translate("tbMainTab", "Enter Age"))
        self.lblTicketType.setText(_translate("tbMainTab", "Select Ticket Type"))
        self.cmbTicketType.setItemText(0, _translate("tbMainTab", "Toplevel"))
        self.cmbTicketType.setItemText(1, _translate("tbMainTab", "Midlevel"))
        self.cmbTicketType.setItemText(2, _translate("tbMainTab", "Courtside"))
        self.btnCalculate.setText(_translate("tbMainTab", "Calculate"))
        self.btnPurchase.setText(_translate("tbMainTab", "Purchase"))
        self.btnClear.setText(_translate("tbMainTab", "Clear"))
        self.btnExit.setText(_translate("tbMainTab", "Exit"))
        self.lblCost.setText(_translate("tbMainTab", "Cost of Puchase"))
        self.grpNumberofTickets.setTitle(_translate("tbMainTab", "Number of Tickets"))
        self.rd1.setText(_translate("tbMainTab", "1"))
        self.radioButton.setText(_translate("tbMainTab", "2"))
        self.rd3.setText(_translate("tbMainTab", "3"))
        self.tbPurchasesMade.setTabText(self.tbPurchasesMade.indexOf(self.tbTicketPurchase), _translate("tbMainTab", "Ticket Purchase"))
        self.lblPurchasesMade.setText(_translate("tbMainTab", "Purchases Made"))
        self.tbPurchasesMade.setTabText(self.tbPurchasesMade.indexOf(self.tbPurchasesMade1), _translate("tbMainTab", "Purchases Made"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tbMainTab = QtWidgets.QMainWindow()
    ui = Ui_tbMainTab()
    ui.setupUi(tbMainTab)
    tbMainTab.show()
    sys.exit(app.exec())
