# Form implementation generated from reading ui file 'studentscores.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from QtWidgets import QMessageBox 


class Ui_studentScores(object):
    def setupUi(self, studentScores):
        studentScores.setObjectName("studentScores")
        studentScores.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        studentScores.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=studentScores)
        self.centralwidget.setObjectName("centralwidget")
        self.lblScore = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblScore.setGeometry(QtCore.QRect(60, 40, 161, 16))
        self.lblScore.setObjectName("lblScore")
        self.txtScore = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtScore.setGeometry(QtCore.QRect(240, 40, 113, 22))
        self.txtScore.setObjectName("txtScore")
        self.btnScore = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnScore.setGeometry(QtCore.QRect(60, 140, 93, 28))
        self.btnScore.setObjectName("btnScore")
        self.btnAverage = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnAverage.setGeometry(QtCore.QRect(210, 140, 171, 28))
        self.btnAverage.setObjectName("btnAverage")
        self.lstScores = QtWidgets.QListWidget(parent=self.centralwidget)
        self.lstScores.setGeometry(QtCore.QRect(440, 120, 331, 371))
        self.lstScores.setObjectName("lstScores")
        self.lblStudentScores = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblStudentScores.setGeometry(QtCore.QRect(550, 80, 121, 20))
        self.lblStudentScores.setObjectName("lblStudentScores")
        studentScores.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=studentScores)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        studentScores.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=studentScores)
        self.statusbar.setObjectName("statusbar")
        studentScores.setStatusBar(self.statusbar)

        self.retranslateUi(studentScores)
        QtCore.QMetaObject.connectSlotsByName(studentScores)
        
        self.btnScore.clicked.connect()
        self.student_scores_list = []
        self.btnAverage.clicked.connect()
        
        
    def calculate_average(self):
        total = 0
        for item in self.student_scores_list:
            total = total + item
            
        average_value = total/len(self.student_scores_list)
        msg = QtWidgets.QMessageBox()
        msg.setText(str(average_value))
        msg.exec()
        
        
    def add_score(self):
        student_score = int(self.txtScore.text())
        self.lstScores.addItem(str(student_score))
        self.student_scores_list.append(student_score)
        

    def retranslateUi(self, studentScores):
        _translate = QtCore.QCoreApplication.translate
        studentScores.setWindowTitle(_translate("studentScores", "Student Scores"))
        self.lblScore.setText(_translate("studentScores", "Enter Student Score"))
        self.btnScore.setText(_translate("studentScores", "Add Score"))
        self.btnAverage.setText(_translate("studentScores", "Calculate Average"))
        self.lblStudentScores.setText(_translate("studentScores", "Student Scores"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    studentScores = QtWidgets.QMainWindow()
    ui = Ui_studentScores()
    ui.setupUi(studentScores)
    studentScores.show()
    sys.exit(app.exec())
