# Form implementation generated from reading ui file 'helloWorld.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox

class Ui_helloWorld(object):
    def setupUi(self, helloWorld):
        helloWorld.setObjectName("helloWorld")
        helloWorld.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        helloWorld.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=helloWorld)
        self.centralwidget.setObjectName("centralwidget")
        self.btnDisplay = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDisplay.setGeometry(QtCore.QRect(330, 230, 131, 51))
        self.btnDisplay.setObjectName("btnDisplay")
        helloWorld.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=helloWorld)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        helloWorld.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=helloWorld)
        self.statusbar.setObjectName("statusbar")
        helloWorld.setStatusBar(self.statusbar)

        self.retranslateUi(helloWorld)
        QtCore.QMetaObject.connectSlotsByName(helloWorld)
        
        #When the button is cocked, call the display function
        self.btnDisplay.clicked.connect(self.display)

    # self indicates, the function belongs to this application
    def display(self):
        # To display hello world,  we first create a message box instance
        msg = QMessageBox()
        # Set the text property of the message box to hello world
        msg.setText("Hello World")
        # Display the message box to the user
        msg.exec()
        

    def retranslateUi(self, helloWorld):
        _translate = QtCore.QCoreApplication.translate
        helloWorld.setWindowTitle(_translate("helloWorld", "Hello World"))
        self.btnDisplay.setText(_translate("helloWorld", "Click Me"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    helloWorld = QtWidgets.QMainWindow()
    ui = Ui_helloWorld()
    ui.setupUi(helloWorld)
    helloWorld.show()
    sys.exit(app.exec())
