# Form implementation generated from reading ui file 'FullName.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.lblFirstName = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblFirstName.setObjectName("lblFirstName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblFirstName)
        self.txtFirstName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtFirstName.setObjectName("txtFirstName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtFirstName)
        self.lblLastName = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblLastName.setObjectName("lblLastName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblLastName)
        self.txtLastName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtLastName.setObjectName("txtLastName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtLastName)
        self.btnFullName = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnFullName.setObjectName("btnFullName")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.btnFullName)
        self.lblFullName = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblFullName.setObjectName("lblFullName")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblFullName)
        self.txtOutput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtOutput.setReadOnly(True)
        self.txtOutput.setObjectName("txtOutput")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtOutput)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        self.menuShow_Full_Name = QtWidgets.QMenu(parent=self.menubar)
        self.menuShow_Full_Name.setObjectName("menuShow_Full_Name")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuShow_Full_Name.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.btnFullName.clicked.connect(self.display_full_name)
        
    def display_full_name(self):
        first_name = self.txtFirstName.text()
        last_name = self.LastName.text()
        
        full_name = first_name+" "+last_name
        
        self.txtOutput.seText(full_name)
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Full Name"))
        self.lblFirstName.setText(_translate("MainWindow", "Enter First Name:"))
        self.lblLastName.setText(_translate("MainWindow", "Enter Last Name:"))
        self.btnFullName.setText(_translate("MainWindow", "Display Full Name"))
        self.lblFullName.setText(_translate("MainWindow", "Full Name:"))
        self.menuShow_Full_Name.setTitle(_translate("MainWindow", "Show Full Name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
