# Form implementation generated from reading ui file 'studentdata.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import pymysql as mdb

class Ui_studentData(object):
    def setupUi(self, studentData):
        studentData.setObjectName("studentData")
        studentData.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        studentData.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=studentData)
        self.centralwidget.setObjectName("centralwidget")
        self.lblId = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblId.setGeometry(QtCore.QRect(144, 90, 131, 20))
        self.lblId.setObjectName("lblId")
        self.lblName = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblName.setGeometry(QtCore.QRect(124, 150, 151, 20))
        self.lblName.setObjectName("lblName")
        self.lblAge = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblAge.setGeometry(QtCore.QRect(134, 210, 141, 20))
        self.lblAge.setObjectName("lblAge")
        self.txtId = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtId.setGeometry(QtCore.QRect(340, 90, 113, 22))
        self.txtId.setObjectName("txtId")
        self.txtName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtName.setGeometry(QtCore.QRect(340, 150, 113, 22))
        self.txtName.setObjectName("txtName")
        self.txtAge = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtAge.setGeometry(QtCore.QRect(340, 210, 113, 22))
        self.txtAge.setObjectName("txtAge")
        self.lblData = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblData.setGeometry(QtCore.QRect(300, 330, 111, 20))
        self.lblData.setObjectName("lblData")
        self.btnInsert = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnInsert.setGeometry(QtCore.QRect(220, 270, 93, 28))
        self.btnInsert.setObjectName("btnInsert")
        self.btnDisplay = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDisplay.setGeometry(QtCore.QRect(350, 270, 93, 28))
        self.btnDisplay.setObjectName("btnDisplay")
        self.lstData = QtWidgets.QListWidget(parent=self.centralwidget)
        self.lstData.setGeometry(QtCore.QRect(230, 360, 256, 192))
        self.lstData.setObjectName("lstData")
        studentData.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=studentData)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        studentData.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=studentData)
        self.statusbar.setObjectName("statusbar")
        studentData.setStatusBar(self.statusbar)

        self.retranslateUi(studentData)
        QtCore.QMetaObject.connectSlotsByName(studentData)
        
        self.btnInsert.clicked.connect(self.insert_data)
        
        self.btnDisplay.clicked.connect(self.display_data)

    def display_data(self) :
        try:
            dbconnection = mdb.connect(host="localhost", port=3306, database="student", user="442user", password="442user")
            
            if (dbconnection) :
                cursor = dbconnection. cursor ()
                cursor.execute ("select * from student_data")
                data = cursor.fetchall ()
                for item in data:
                    print (item)
        except Exception as e:
            print (e)
        finally:
            if (dbconnection):
                    dbconnection.close()
        
     
        
    def insert_data(self):
        try:
            sid = int(self.txtId.text())
            sname = self.txtName.text()
            sage = int(self.txtAge.text())
            
            dbconnection - mdb.connect(host="localhost", port=3306, database="student", user="442user",
            password="442user")
            
            if(dbconnection):
                cursor = dbconnection.cursor()
                cursor.execute("insert into student_data(studentid, studentname, studentage) values(%s,%s,%s)", [
                sid, sname, sage])
                dbconnection.commit()
                print("data added")
            else:
                print("db connection failed")
            except Exception as e:
                print(e)
            finally 
                if(dbconnection):
                    dbconnection.close()
            
            
    def retranslateUi(self, studentData):
        _translate = QtCore.QCoreApplication.translate
        studentData.setWindowTitle(_translate("studentData", "Student Data"))
        self.lblId.setText(_translate("studentData", "Enter Student ID"))
        self.lblName.setText(_translate("studentData", "Enter Student Name"))
        self.lblAge.setText(_translate("studentData", "Enter Student Age"))
        self.lblData.setText(_translate("studentData", "Student Data"))
        self.btnInsert.setText(_translate("studentData", "Insert"))
        self.btnDisplay.setText(_translate("studentData", "Display"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    studentData = QtWidgets.QMainWindow()
    ui = Ui_studentData()
    ui.setupUi(studentData)
    studentData.show()
    sys.exit(app.exec())
