# Form implementation generated from reading ui file 'fruitpurchase.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_fruitPurchase(object):
    def setupUi(self, fruitPurchase):
        fruitPurchase.setObjectName("fruitPurchase")
        fruitPurchase.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        fruitPurchase.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=fruitPurchase)
        self.centralwidget.setObjectName("centralwidget")
        self.lblFruit = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblFruit.setGeometry(QtCore.QRect(80, 40, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblFruit.setFont(font)
        self.lblFruit.setObjectName("lblFruit")
        self.lblQuantity = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblQuantity.setGeometry(QtCore.QRect(80, 110, 221, 16))
        self.lblQuantity.setObjectName("lblQuantity")
        self.lblCost = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblCost.setGeometry(QtCore.QRect(80, 170, 151, 16))
        self.lblCost.setObjectName("lblCost")
        self.txtCost = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtCost.setGeometry(QtCore.QRect(300, 170, 113, 22))
        self.txtCost.setReadOnly(True)
        self.txtCost.setObjectName("txtCost")
        self.txtQuantity = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtQuantity.setGeometry(QtCore.QRect(300, 100, 113, 22))
        self.txtQuantity.setObjectName("txtQuantity")
        self.cmbFruit = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cmbFruit.setGeometry(QtCore.QRect(290, 40, 73, 22))
        self.cmbFruit.setObjectName("cmbFruit")
        self.cmbFruit.addItem("")
        self.cmbFruit.addItem("")
        self.cmbFruit.addItem("")
        self.cmbFruit.addItem("")
        self.cmbFruit.addItem("")
        self.lblPrice = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblPrice.setGeometry(QtCore.QRect(420, 40, 121, 16))
        self.lblPrice.setText("")
        self.lblPrice.setObjectName("lblPrice")
        self.btnCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCalculate.setGeometry(QtCore.QRect(470, 100, 171, 28))
        self.btnCalculate.setObjectName("btnCalculate")
        fruitPurchase.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=fruitPurchase)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        fruitPurchase.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=fruitPurchase)
        self.statusbar.setObjectName("statusbar")
        fruitPurchase.setStatusBar(self.statusbar)

        self.retranslateUi(fruitPurchase)
        QtCore.QMetaObject.connectSlotsByName(fruitPurchase)
        
        self.fruit_price_per_pound = {"Apple":3.50, "Orange":3.99, "Mango":4.25, "Kiwi":5.00, "Banana":1.25}
        
        self.btnCalculate.clicked.connect(self.calculate_cost)
        
    def calculate_cost(self):
        current_fruit = self.cmbFruit.currentText()
        number_of_pounds = int(self.txtQuantity.text())
        price_per_pound = self.fruit_price_per_pound.get(current_fruit)
        cost = number_of_pounds * price_per_pound
        self.txtCost.setText(f"${cost:.2f}")
        

    def retranslateUi(self, fruitPurchase):
        _translate = QtCore.QCoreApplication.translate
        fruitPurchase.setWindowTitle(_translate("fruitPurchase", "Fruit Purchase"))
        self.lblFruit.setText(_translate("fruitPurchase", "Select a Fruit"))
        self.lblQuantity.setText(_translate("fruitPurchase", "Enter Number of Pounds"))
        self.lblCost.setText(_translate("fruitPurchase", "Cost of Purchase"))
        self.cmbFruit.setItemText(0, _translate("fruitPurchase", "Apple"))
        self.cmbFruit.setItemText(1, _translate("fruitPurchase", "Orange"))
        self.cmbFruit.setItemText(2, _translate("fruitPurchase", "Mango"))
        self.cmbFruit.setItemText(3, _translate("fruitPurchase", "Kiwi"))
        self.cmbFruit.setItemText(4, _translate("fruitPurchase", "Banana"))
        self.btnCalculate.setText(_translate("fruitPurchase", "Calculate Cost"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    fruitPurchase = QtWidgets.QMainWindow()
    ui = Ui_fruitPurchase()
    ui.setupUi(fruitPurchase)
    fruitPurchase.show()
    sys.exit(app.exec())
