# Form implementation generated from reading ui file 'gradecalculator.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QWidgets import QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblScore = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblScore.setGeometry(QtCore.QRect(120, 100, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblScore.setFont(font)
        self.lblScore.setObjectName("lblScore")
        self.txtScore = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtScore.setGeometry(QtCore.QRect(380, 100, 113, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.txtScore.setFont(font)
        self.txtScore.setObjectName("txtScore")
        self.btnCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCalculate.setGeometry(QtCore.QRect(200, 190, 221, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnCalculate.setFont(font)
        self.btnCalculate.setObjectName("btnCalculate")
        self.lblGrade = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblGrade.setGeometry(QtCore.QRect(130, 300, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblGrade.setFont(font)
        self.lblGrade.setObjectName("lblGrade")
        self.txtGrade = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtGrade.setGeometry(QtCore.QRect(380, 300, 113, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.txtGrade.setFont(font)
        self.txtGrade.setReadOnly(True)
        self.txtGrade.setObjectName("txtGrade")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuGrade_Calculator = QtWidgets.QMenu(parent=self.menubar)
        self.menuGrade_Calculator.setObjectName("menuGrade_Calculator")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuGrade_Calculator.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.btnCalculate.clicked.connect(self.calculate_grade)
        
    def calculate_grade(self):
        input_value = self.txtScore.text()
        if(input_value.isdigit()):
            student_score = int(input_value)
            if(student_score >=0 and student_score <=100:
                if(student_score >= 90):
                    grade = "A"
                elif((student_score >= 80):
                    grade = "B"
                elif((student_score >= 70):
                    grade = "C"
                elif((student_score >= 60):
                    grade = "D"
                else:
                    grade = "F"
                self.txtGrade.setText(grade)
            else:
                msg = QMessageBox()
                msg.setText("Please enter a score between 0 and 100")
                msg.exec()
        else:
            msg = QMessageBox()
            msg.setText("Please enter a numeric score")
            msg.exec()
            
                             
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblScore.setText(_translate("MainWindow", "Enter Student Score"))
        self.btnCalculate.setText(_translate("MainWindow", "Calculate Grade"))
        self.lblGrade.setText(_translate("MainWindow", "Student Grade"))
        self.menuGrade_Calculator.setTitle(_translate("MainWindow", "Grade Calculator"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
