# Form implementation generated from reading ui file 'evenorodd.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblNumber = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblNumber.setGeometry(QtCore.QRect(110, 90, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblNumber.setFont(font)
        self.lblNumber.setObjectName("lblNumber")
        self.txtNumber = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtNumber.setGeometry(QtCore.QRect(370, 90, 113, 22))
        self.txtNumber.setObjectName("txtNumber")
        self.btnResult = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnResult.setGeometry(QtCore.QRect(260, 200, 161, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnResult.setFont(font)
        self.btnResult.setObjectName("btnResult")
        self.lblResult = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblResult.setGeometry(QtCore.QRect(110, 320, 221, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblResult.setFont(font)
        self.lblResult.setObjectName("lblResult")
        self.txtResult = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtResult.setGeometry(QtCore.QRect(420, 320, 113, 22))
        self.txtResult.setReadOnly(True)
        self.txtResult.setObjectName("txtResult")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuEven_or_Odd = QtWidgets.QMenu(parent=self.menubar)
        self.menuEven_or_Odd.setObjectName("menuEven_or_Odd")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuEven_or_Odd.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.btnResult.clicked.connect(slef.even_or_odd)
    def even_or_odd(self):
        number = self.txtNumber.text()
        
        interger_number = int(number)
        
        if (interger_number %2 ==0):
            self.txtResult.setText("Even")
        else:
            self.txtResult.setText("Odd")
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblNumber.setText(_translate("MainWindow", "Enter a Number"))
        self.btnResult.setText(_translate("MainWindow", "Even or Odd?"))
        self.lblResult.setText(_translate("MainWindow", "Is the number even or odd?"))
        self.menuEven_or_Odd.setTitle(_translate("MainWindow", "Even or Odd?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
