# Form implementation generated from reading ui file 'CoffeeShop.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
# Price Constraints 
LATTE_PRICE = 4.50 
CAPP_PRICE = 5.00 
ESP_PRICE = 5.50 
LARGE_UPCHARGE = 2.00


class Ui_CoffeeShopMW(object):
    def setupUi(self, CoffeeShopMW):
        CoffeeShopMW.setObjectName("CoffeeShopMW")
        CoffeeShopMW.resize(957, 755)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        CoffeeShopMW.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=CoffeeShopMW)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblShopName = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblShopName.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.lblShopName.setObjectName("lblShopName")
        self.verticalLayout.addWidget(self.lblShopName)
        self.lbllatte = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbllatte.setEnabled(True)
        self.lbllatte.setObjectName("lbllatte")
        self.verticalLayout.addWidget(self.lbllatte)
        self.leLatte = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.leLatte.setObjectName("leLatte")
        self.verticalLayout.addWidget(self.leLatte)
        self.lblPriceLatte = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblPriceLatte.setObjectName("lblPriceLatte")
        self.verticalLayout.addWidget(self.lblPriceLatte)
        self.lblCapp = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblCapp.setObjectName("lblCapp")
        self.verticalLayout.addWidget(self.lblCapp)
        self.leCapp = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.leCapp.setObjectName("leCapp")
        self.verticalLayout.addWidget(self.leCapp)
        self.lblPriceCap = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblPriceCap.setObjectName("lblPriceCap")
        self.verticalLayout.addWidget(self.lblPriceCap)
        self.lblEsp = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblEsp.setObjectName("lblEsp")
        self.verticalLayout.addWidget(self.lblEsp)
        self.leEsp = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.leEsp.setObjectName("leEsp")
        self.verticalLayout.addWidget(self.leEsp)
        self.lblPriceEs = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblPriceEs.setObjectName("lblPriceEs")
        self.verticalLayout.addWidget(self.lblPriceEs)
        self.lblSize = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblSize.setObjectName("lblSize")
        self.verticalLayout.addWidget(self.lblSize)
        self.leSize = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.leSize.setObjectName("leSize")
        self.verticalLayout.addWidget(self.leSize)
        self.container = QtWidgets.QWidget(parent=self.centralwidget)
        self.container.setObjectName("container")
        self.gridLayout = QtWidgets.QGridLayout(self.container)
        self.gridLayout.setObjectName("gridLayout")
        self.btnOrder = QtWidgets.QPushButton(parent=self.container)
        self.btnOrder.setObjectName("btnOrder")
        self.gridLayout.addWidget(self.btnOrder, 0, 0, 1, 1)
        self.btnClear = QtWidgets.QPushButton(parent=self.container)
        self.btnClear.setObjectName("btnClear")
        self.gridLayout.addWidget(self.btnClear, 0, 1, 1, 1)
        self.btnExit = QtWidgets.QPushButton(parent=self.container)
        self.btnExit.setObjectName("btnExit")
        self.gridLayout.addWidget(self.btnExit, 0, 2, 1, 1)
        self.leTotal = QtWidgets.QLineEdit(parent=self.container)
        self.leTotal.setReadOnly(True)
        self.leTotal.setObjectName("leTotal")
        self.gridLayout.addWidget(self.leTotal, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.container)
        CoffeeShopMW.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=CoffeeShopMW)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 957, 26))
        self.menubar.setObjectName("menubar")
        self.menuLatte_Lounge = QtWidgets.QMenu(parent=self.menubar)
        self.menuLatte_Lounge.setObjectName("menuLatte_Lounge")
        CoffeeShopMW.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=CoffeeShopMW)
        self.statusbar.setObjectName("statusbar")
        CoffeeShopMW.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuLatte_Lounge.menuAction())
        # make read only
        self.leTotal.setReadOnly(True)
        # Set up Validators
        self._setupValidatorsAndSignals()
        self.retranslateUi(CoffeeShopMW)
        QtCore.QMetaObject.connectSlotsByName(CoffeeShopMW)
        
    # Attach input validators and connect the Order button. 
    # Quantities must be non-negative integers 
    # Size must be Small or Large
    def _setupValidatorsAndSignals(self) : 
        int_validator = QtGui.QIntValidator(0,10_000, self.centralwidget) 
        self.leLatte.setValidator(int_validator) 
        self.leCapp.setValidator(int_validator) 
        self.leEsp.setValidator(int_validator)
        
    # Click to order
        self.btnOrder.clicked.connect(self.calculate_total)
        
    # Click to clear
        if hasattr(self, "btnClear"):
            self.btnClear.clicked.connect(self.clear_all)
    # Click to Quit        
        if hasattr(self, "btnExit"):
            self.btnExit.clicked.connect(QtWidgets.QApplication.instance().quit)    
           
    #Reset all inputs to default       
    def clear_all(self):
        self.leLatte.setText("0")
        self.leCapp.setText("0")
        self.leEsp.setText("0")
        self.leSize.setText("Small")
        
    # Reset size
        if hasattr(self, "cbSize"):
            self.cbSize.setCurrentText("Small")
        
    # Clear total
        self.leTotal.clear()
        
    # Quit App
    def _quit_app(self):
        self._quit_app
    
# Make empty string count as 0.
    def _get_qty(self, line_edit: QtWidgets.QLineEdit) -> int:
        t = line_edit.text().strip()
        if not t:
            return 0
        if line_edit.hasAcceptableInput():
            return int(t)
        return 0 
    # Return the size     
    def _normalize_size(self) -> str:
        return self.leSize.text().strip().lower()
        
    # Calculate the total by multiplying the quantity by price
    # Add the large upcharge if necessary
    def calculate_total(self):
        n_latte = self._get_qty(self.leLatte)
        n_capp = self._get_qty(self.leCapp)
        n_esp = self._get_qty(self.leEsp)
     # Give warning if size is not small or large    
        size_norm = self._normalize_size()
        if size_norm not in ("small","large"):
            QtWidgets.QMessageBox.warning(
            self.centralwidget,
            "Invalid Size",
            "Enter size as 'Small' or 'Large'."
            )
            return
            
    # Base cost
        base = ( 
        n_latte * LATTE_PRICE +
        n_capp * CAPP_PRICE +
        n_esp * ESP_PRICE
        )
    # Large Upcharge
        total_drinks = n_latte + n_capp + n_esp
        upcharge = LARGE_UPCHARGE * total_drinks if size_norm == "large" else 0.0
    # display
        total = base + upcharge
        self.leTotal.setText(f"${total:,.2f}")
    
    def retranslateUi(self, CoffeeShopMW):
        _translate = QtCore.QCoreApplication.translate
        CoffeeShopMW.setWindowTitle(_translate("CoffeeShopMW", "MainWindow"))
        self.lblShopName.setText(_translate("CoffeeShopMW", "Latte Lounge"))
        self.lbllatte.setText(_translate("CoffeeShopMW", "Number of Lattes"))
        self.leLatte.setText(_translate("CoffeeShopMW", "0"))
        self.lblPriceLatte.setText(_translate("CoffeeShopMW", f"Latte: ${LATTE_PRICE:.2f}"))
        self.lblCapp.setText(_translate("CoffeeShopMW", "Number Of Cappuccinos "))
        self.leCapp.setText(_translate("CoffeeShopMW", "0"))
        self.lblPriceCap.setText(_translate("CoffeeShopMW", f"Cappucino: ${CAPP_PRICE:.2f}"))
        self.lblEsp.setText(_translate("CoffeeShopMW", "Number of Espressos"))
        self.leEsp.setText(_translate("CoffeeShopMW", "0"))
        self.lblPriceEs.setText(_translate("CoffeeShopMW", f"Espresso: ${ESP_PRICE:.2f}"))
        self.lblSize.setText(_translate("CoffeeShopMW", "Size (Small or Large + $2.00)"))
        self.leSize.setText(_translate("CoffeeShopMW", "Small"))
        self.btnOrder.setText(_translate("CoffeeShopMW", "Order"))
        self.leTotal.setText(_translate("CoffeeShopMW", "Total Cost"))
        self.btnClear.setText(_translate("CoffeeShopMW", "Clear"))
        self.btnExit.setText(_translate("CoffeeShopMW", "Exit"))
        self.menuLatte_Lounge.setTitle(_translate("CoffeeShopMW", "Latte Lounge"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mw = QtWidgets.QMainWindow()
    ui = Ui_CoffeeShopMW()
    ui.setupUi(mw)
    mw.show()
    sys.exit(app.exec())    
    
            
