# Form implementation generated from reading ui file 'financialplanner.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FinancialPlanner(object):
    def setupUi(self, FinancialPlanner):
        FinancialPlanner.setObjectName("FinancialPlanner")
        FinancialPlanner.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        FinancialPlanner.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=FinancialPlanner)
        self.centralwidget.setObjectName("centralwidget")
        self.lblDeposit = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblDeposit.setGeometry(QtCore.QRect(70, 80, 241, 16))
        self.lblDeposit.setObjectName("lblDeposit")
        self.txtDeposit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtDeposit.setGeometry(QtCore.QRect(370, 80, 113, 22))
        self.txtDeposit.setObjectName("txtDeposit")
        self.lblTarget = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTarget.setGeometry(QtCore.QRect(70, 180, 251, 16))
        self.lblTarget.setObjectName("lblTarget")
        self.txtTarget = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTarget.setGeometry(QtCore.QRect(380, 180, 113, 22))
        self.txtTarget.setObjectName("txtTarget")
        self.lblPlan = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblPlan.setGeometry(QtCore.QRect(100, 290, 181, 20))
        self.lblPlan.setObjectName("lblPlan")
        self.cmbPlan = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cmbPlan.setGeometry(QtCore.QRect(380, 290, 121, 22))
        self.cmbPlan.setObjectName("cmbPlan")
        self.cmbPlan.addItem("")
        self.cmbPlan.addItem("")
        self.cmbPlan.addItem("")
        self.btnCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCalculate.setGeometry(QtCore.QRect(270, 480, 121, 28))
        self.btnCalculate.setObjectName("btnCalculate")
        self.lblTime = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTime.setGeometry(QtCore.QRect(90, 380, 151, 16))
        self.lblTime.setObjectName("lblTime")
        self.txtTime = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTime.setGeometry(QtCore.QRect(390, 380, 113, 22))
        self.txtTime.setReadOnly(True)
        self.txtTime.setObjectName("txtTime")
        FinancialPlanner.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=FinancialPlanner)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        self.menuFinancial_Planner = QtWidgets.QMenu(parent=self.menubar)
        self.menuFinancial_Planner.setObjectName("menuFinancial_Planner")
        FinancialPlanner.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=FinancialPlanner)
        self.statusbar.setObjectName("statusbar")
        FinancialPlanner.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFinancial_Planner.menuAction())

        self.retranslateUi(FinancialPlanner)
        QtCore.QMetaObject.connectSlotsByName(FinancialPlanner)
        
        self.btnCalculate.clciked.connect(self.calaculate_time)
        
    def calculate_time(self):
        annual_amount = int(self.ttxDeposit.tect())
        target_amount = int(self.txtTarget.text())
        retirement_plan = self.cmbPlan.currentText()
        
        if(retirement_plan == "Plan 2040"):
            rate = 7.0
        elif(retirement_plan == "Plan 2050"):
            rate = 6.0
        else: 
            rate = 5.0
        
        current_portfolio_amount = 0
        time_takrn = 0
        
        while(current_portfolio_amount < target_amount):
            current_portfolio_anmount = (current_portfolio_amount + annual_amount) * (1 + rate/100)
            time_taken = time_taken + 1 
        
        self.txtTime.setText(str(time_taken))
        
        
    

    def retranslateUi(self, FinancialPlanner):
        _translate = QtCore.QCoreApplication.translate
        FinancialPlanner.setWindowTitle(_translate("FinancialPlanner", "Financial Planer"))
        self.lblDeposit.setText(_translate("FinancialPlanner", "Enter Annual Deposit Amount"))
        self.lblTarget.setText(_translate("FinancialPlanner", "Enter Target Portfolio Amount"))
        self.lblPlan.setText(_translate("FinancialPlanner", "Select Retirement Plan"))
        self.cmbPlan.setItemText(0, _translate("FinancialPlanner", "Plan 2040"))
        self.cmbPlan.setItemText(1, _translate("FinancialPlanner", "Plan 2050"))
        self.cmbPlan.setItemText(2, _translate("FinancialPlanner", "Plan 2060"))
        self.btnCalculate.setText(_translate("FinancialPlanner", "Calculate"))
        self.lblTime.setText(_translate("FinancialPlanner", "Number of Years"))
        self.menuFinancial_Planner.setTitle(_translate("FinancialPlanner", "Financial Planner"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FinancialPlanner = QtWidgets.QMainWindow()
    ui = Ui_FinancialPlanner()
    ui.setupUi(FinancialPlanner)
    FinancialPlanner.show()
    sys.exit(app.exec())
