# Form implementation generated from reading ui file 'StudentApp.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

# Nicolai Mage BUS 442 Project 4 Fall 2025



from PyQt6 import QtCore, QtGui, QtWidgets

# create SQL Connection and configuration 
import pymysql as mdb
from PyQt6.QtWidgets import QMessageBox
import os
DB_HOST = "localhost"
DB_USER = "442user"
DB_PASSWORD = "442user"
DB_NAME = "project4db"
DB_PORT = 3306
def get_connection():
    return mdb.connect(
        host=DB_HOST,
        user=DB_USER,
        password=DB_PASSWORD,
        database=DB_NAME,
        port=DB_PORT,
        cursorclass=mdb.cursors.DictCursor
    )


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.tab)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEditStudentName = QtWidgets.QLineEdit(parent=self.tab)
        self.lineEditStudentName.setObjectName("lineEditStudentName")
        self.verticalLayout.addWidget(self.lineEditStudentName)
        self.label_3 = QtWidgets.QLabel(parent=self.tab)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEditStudentId = QtWidgets.QLineEdit(parent=self.tab)
        self.lineEditStudentId.setObjectName("lineEditStudentId")
        self.verticalLayout.addWidget(self.lineEditStudentId)
        self.label_2 = QtWidgets.QLabel(parent=self.tab)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEditStudentScore = QtWidgets.QLineEdit(parent=self.tab)
        self.lineEditStudentScore.setObjectName("lineEditStudentScore")
        self.verticalLayout.addWidget(self.lineEditStudentScore)
        self.pushButtonInsertData = QtWidgets.QPushButton(parent=self.tab)
        self.pushButtonInsertData.setObjectName("pushButtonInsertData")
        self.verticalLayout.addWidget(self.pushButtonInsertData)
        self.pushButtonDisplayData = QtWidgets.QPushButton(parent=self.tab)
        self.pushButtonDisplayData.setObjectName("pushButtonDisplayData")
        self.verticalLayout.addWidget(self.pushButtonDisplayData)
        self.tableWidgetStudents = QtWidgets.QTableWidget(parent=self.tab)
        self.tableWidgetStudents.setObjectName("tableWidgetStudents")
        self.tableWidgetStudents.setColumnCount(0)
        self.tableWidgetStudents.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidgetStudents)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout.setObjectName("gridLayout")
        self.listWidgetGrades = QtWidgets.QListWidget(parent=self.tab_2)
        self.listWidgetGrades.setObjectName("listWidgetGrades")
        self.gridLayout.addWidget(self.listWidgetGrades, 0, 0, 1, 1)
        self.pushButtonExportData = QtWidgets.QPushButton(parent=self.tab_2)
        self.pushButtonExportData.setObjectName("pushButtonExportData")
        self.gridLayout.addWidget(self.pushButtonExportData, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuStudent_App = QtWidgets.QMenu(parent=self.menubar)
        self.menuStudent_App.setObjectName("menuStudent_App")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuStudent_App.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
 
        # Connect the buttons
        self.pushButtonInsertData.clicked.connect(self.insert_data)
        self.pushButtonDisplayData.clicked.connect(self.display_data)
        self.pushButtonExportData.clicked.connect(self.export_data)
        # Load grades when the tab is changed 
        self.tabWidget.currentChanged.connect(self.load_grades_tab)
        
        # Load data from file on start
        self.load_initial_file()
    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Student Name: "))
        self.label_3.setText(_translate("MainWindow", "Student ID:"))
        self.label_2.setText(_translate("MainWindow", "Student Score:"))
        self.pushButtonInsertData.setText(_translate("MainWindow", "Insert Data"))
        self.pushButtonDisplayData.setText(_translate("MainWindow", "Display Data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Student Info"))
        self.pushButtonExportData.setText(_translate("MainWindow", "Export Data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Student Grade"))
        self.menuStudent_App.setTitle(_translate("MainWindow", "Student App"))
        
    # Load the students file
    # Open DB connection 
    # Skip duplicate
    def load_initial_file(self):
        try:
            conn = get_connection()
            cursor = conn.cursor()

            file_path = "Students.txt"
            if not os.path.exists(file_path):
                return

            with open(file_path, "r") as f:
                for line in f:
                    parts = line.strip().split(",")

                    if len(parts) != 3:
                        continue

                    sid = parts[0].strip()
                    name = parts[1].strip()
                    score = parts[2].strip()

                    if not sid or not name or not score:
                        continue

                    cursor.execute("SELECT student_id FROM student WHERE student_id=%s", (sid,))
                    if cursor.fetchone():
                        continue

                    cursor.execute("""
                        INSERT INTO student(student_id, student_name, student_score)
                        VALUES (%s, %s, %s)
                    """, (sid, name, score))

            conn.commit()
                
        except Exception as e:
            QMessageBox.critical(None, "Error Loading File", str(e))
        finally:
            if conn:
                conn.close()
                
    # Insert the Data from user into DB           
    def insert_data(self):
        # Get the input values
        sid = self.lineEditStudentId.text().strip()
        name = self.lineEditStudentName.text().strip()
        score = self.lineEditStudentScore.text().strip()
        # Validate the required fields/numbers
        if not sid or not name or not score:
            QMessageBox.warning(None, "Input Error", "All fields are required.")
            return

        if not sid.isdigit():
            QMessageBox.warning(None, "Input Error", "Student ID must be an integer.")
            return

        if not score.isdigit():
            QMessageBox.warning(None, "Input Error", "Score must be an integer.")
            return

        try:
            conn = get_connection()
            cursor = conn.cursor()

            cursor.execute("SELECT student_id FROM student WHERE student_id=%s", (sid,))
            if cursor.fetchone():
                QMessageBox.warning(None, "Duplicate ID", "Student ID already exists.")
                return

            cursor.execute("""
                INSERT INTO student(student_id, student_name, student_score)
                VALUES (%s, %s, %s)
            """, (sid, name, score))
            conn.commit()

            QMessageBox.information(None, "Success", "Student added successfully!")

            self.lineEditStudentId.clear()
            self.lineEditStudentName.clear()
            self.lineEditStudentScore.clear()

        except Exception as e:
            QMessageBox.critical(None, "Database Error", str(e))
        finally:
            if conn:
                conn.close()
                
    # Display the Data on the table
    def display_data(self):
        try:
            conn = get_connection()
            cursor = conn.cursor()
            cursor.execute("SELECT * FROM student")
            rows = cursor.fetchall()

            self.tableWidgetStudents.setRowCount(len(rows))
            self.tableWidgetStudents.setColumnCount(3)
            self.tableWidgetStudents.setHorizontalHeaderLabels(
                ["Student ID", "Student Name", "Student Score"]
            )

            for r, row in enumerate(rows):
                self.tableWidgetStudents.setItem(r, 0, QtWidgets.QTableWidgetItem(str(row["studentid"])))
                self.tableWidgetStudents.setItem(r, 1, QtWidgets.QTableWidgetItem(row["studentname"]))
                self.tableWidgetStudents.setItem(r, 2, QtWidgets.QTableWidgetItem(str(row["studentscore"])))

        except Exception as e:
            QMessageBox.critical(None, "Display Error", str(e))
        finally:
            if conn:
                conn.close()
                
    # Grade Calculation on the Scale
    def calculate_grade(self, s):
        s = int(s)
        if s < 60: return 'F'
        if s < 70: return 'D'
        if s < 80: return 'C'
        if s < 90: return 'B'
        return 'A'
        
    # Load the Grades for the second tab
    # Calculate the grade letter from our grade scale function
    def load_grades_tab(self, index):
        if index != 1:
            return

        try:
            conn = get_connection()
            cursor = conn.cursor()
            cursor.execute("SELECT * FROM student")
            rows = cursor.fetchall()

            self.listWidgetGrades.clear()

            for row in rows:
                grade = self.calculate_grade(row["student_score"])
                item = f"ID: {row['student_id']} | Name: {row['student_name']} | Grade: {grade}"
                self.listWidgetGrades.addItem(item)

        except Exception as e:
            QMessageBox.critical(None, "Grade Error", str(e))
        finally:
            if conn:
                conn.close()

    # Export the Data, student ID, name and grade into the studentgrades.txt
    def export_data(self):
        try:
            conn = get_connection()
            cursor = conn.cursor()
            cursor.execute("SELECT * FROM student")
            rows = cursor.fetchall()

            with open("studentgrades.txt", "w") as f:
                for row in rows:
                    grade = self.calculate_grade(row["student_score"])
                    f.write(f"{row['student_id']}, {row['student_name']}, {grade}\n")

            QMessageBox.information(None, "Success", "Exported to studentgrades.txt")

        except Exception as e:
            QMessageBox.critical(None, "Export Error", str(e))
        finally:
            if conn:
                conn.close()    
                
               
                     
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
