# Form implementation generated from reading ui file 'filehandeling.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_fileHandling(object):
    def setupUi(self, fileHandling):
        fileHandling.setObjectName("fileHandling")
        fileHandling.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        fileHandling.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=fileHandling)
        self.centralwidget.setObjectName("centralwidget")
        self.lstScores = QtWidgets.QListWidget(parent=self.centralwidget)
        self.lstScores.setGeometry(QtCore.QRect(140, 60, 451, 311))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lstScores.setFont(font)
        self.lstScores.setObjectName("lstScores")
        self.lblScores = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblScores.setGeometry(QtCore.QRect(300, 30, 211, 16))
        self.lblScores.setObjectName("lblScores")
        self.btnCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCalculate.setGeometry(QtCore.QRect(310, 390, 93, 28))
        self.btnCalculate.setObjectName("btnCalculate")
        self.txtAvg = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtAvg.setGeometry(QtCore.QRect(410, 460, 113, 22))
        self.txtAvg.setObjectName("txtAvg")
        self.lblAverage = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblAverage.setGeometry(QtCore.QRect(190, 460, 151, 16))
        self.lblAverage.setObjectName("lblAverage")
        fileHandling.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=fileHandling)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        fileHandling.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=fileHandling)
        self.statusbar.setObjectName("statusbar")
        fileHandling.setStatusBar(self.statusbar)

        self.retranslateUi(fileHandling)
        QtCore.QMetaObject.connectSlotsByName(fileHandling)
        
         # Creating an empty dictionary to store student scores (key=name, value=score)
        self.scores_dictionary = {}

        self.load_data("student_scores.txt")
        
        self.btnCalculate.clicked.connect (self.calculate_average)

    def calculate_average(self) :
        if(len(self.scores_dictionary) > 0) :
            total = 0
            for value in self.scores_dictionary.values () :
                total = total + value

            average = total/len(self.scores_dictionary)
            self.txtAverage.setText (f"{average :.2f}")
        else:
            msg = QtWidgets.QMessageBox ()
            msg.setText ("No student data to calculate average")
            msg.exec ()

    def load_data(self, filename) :
        with open(filename, "r") as file:
            for line in file:
                data = line.split (",")
                self.scores_dictionary [data[0]] = int(data[1].strip ())
                self.lstScores.addItem(f"{data[0]}  {data [1].strip ()}")


    def retranslateUi(self, fileHandling):
        _translate = QtCore.QCoreApplication.translate
        fileHandling.setWindowTitle(_translate("fileHandling", "File Handling"))
        self.lblScores.setText(_translate("fileHandling", "Student Scores"))
        self.btnCalculate.setText(_translate("fileHandling", "Calculate"))
        self.lblAverage.setText(_translate("fileHandling", "Average Score"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    fileHandling = QtWidgets.QMainWindow()
    ui = Ui_fileHandling()
    ui.setupUi(fileHandling)
    fileHandling.show()
    sys.exit(app.exec())
