# Form implementation generated from reading ui file 'financialplanner2.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FinancialPlanner2(object):
    def setupUi(self, FinancialPlanner2):
        FinancialPlanner2.setObjectName("FinancialPlanner2")
        FinancialPlanner2.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        FinancialPlanner2.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=FinancialPlanner2)
        self.centralwidget.setObjectName("centralwidget")
        self.lblAmount = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblAmount.setGeometry(QtCore.QRect(80, 90, 231, 16))
        self.lblAmount.setObjectName("lblAmount")
        self.txtAmount = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtAmount.setGeometry(QtCore.QRect(350, 90, 113, 22))
        self.txtAmount.setObjectName("txtAmount")
        self.lblTime = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTime.setGeometry(QtCore.QRect(90, 210, 211, 16))
        self.lblTime.setObjectName("lblTime")
        self.txtTime = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTime.setGeometry(QtCore.QRect(350, 200, 113, 22))
        self.txtTime.setObjectName("txtTime")
        self.chkRate = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.chkRate.setGeometry(QtCore.QRect(20, 300, 131, 20))
        self.chkRate.setObjectName("chkRate")
        self.btnCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCalculate.setGeometry(QtCore.QRect(160, 300, 93, 28))
        self.btnCalculate.setObjectName("btnCalculate")
        self.btnClear = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnClear.setGeometry(QtCore.QRect(310, 300, 93, 28))
        self.btnClear.setObjectName("btnClear")
        self.btnExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(480, 300, 93, 28))
        self.btnExit.setObjectName("btnExit")
        self.lstOutput = QtWidgets.QListWidget(parent=self.centralwidget)
        self.lstOutput.setGeometry(QtCore.QRect(140, 380, 501, 171))
        self.lstOutput.setObjectName("lstOutput")
        self.lblOutput = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblOutput.setGeometry(QtCore.QRect(230, 360, 271, 20))
        self.lblOutput.setObjectName("lblOutput")
        FinancialPlanner2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=FinancialPlanner2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        self.menufinancial_planner_2 = QtWidgets.QMenu(parent=self.menubar)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.menufinancial_planner_2.setFont(font)
        self.menufinancial_planner_2.setObjectName("menufinancial_planner_2")
        FinancialPlanner2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=FinancialPlanner2)
        self.statusbar.setObjectName("statusbar")
        FinancialPlanner2.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menufinancial_planner_2.menuAction())

        self.retranslateUi(FinancialPlanner2)
        QtCore.QMetaObject.connectSlotsByName(FinancialPlanner2)
        
        self.btnCalculate.clicked.connect(self.calculate_portfolio_balance)
        
    def calculate_portfolio_balance(self):
        annual_amount = int(self.txtAmount.text())
        number_of_years = int(self.txtTime.text())
        
        if(self.chkRate.isChecked):
            rate = 7.0
        else:
            rate = 5.0
            
        initial_amount = 0 
        for time in range(1, number_of_years +1):
            initial_amount = (initial_amount + annual_amount)*(1 + rate/100)
            self.lstOutput.addItem(str(time)+" "+ str(initial_amount))
            

    def retranslateUi(self, FinancialPlanner2):
        _translate = QtCore.QCoreApplication.translate
        FinancialPlanner2.setWindowTitle(_translate("FinancialPlanner2", "Financial Planner 2"))
        self.lblAmount.setText(_translate("FinancialPlanner2", "Enter Annual Deposit Amount"))
        self.lblTime.setText(_translate("FinancialPlanner2", "Number of Years to Invest"))
        self.chkRate.setText(_translate("FinancialPlanner2", "High Risk"))
        self.btnCalculate.setText(_translate("FinancialPlanner2", "Calculate"))
        self.btnClear.setText(_translate("FinancialPlanner2", "Clear"))
        self.btnExit.setText(_translate("FinancialPlanner2", "Exit"))
        self.lblOutput.setText(_translate("FinancialPlanner2", "Portfolio Balance After Each Year"))
        self.menufinancial_planner_2.setTitle(_translate("FinancialPlanner2", "financial planner 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FinancialPlanner2 = QtWidgets.QMainWindow()
    ui = Ui_FinancialPlanner2()
    ui.setupUi(FinancialPlanner2)
    FinancialPlanner2.show()
    sys.exit(app.exec())
